config/routes.rb
Rails.application.routes.draw do
  resources :avaliacaos
  resources :alunos
  resources :atividades
  resources :disciplinas
  devise_for :users
  resources :turmas
  get 'welcome/index'

  root 'welcome#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/disciplina.rb
class Disciplina < ApplicationRecord
  belongs_to :turma
  has_many :atividades, dependent: :destroy

  validates :nome, presence: true, length: {in: 4..30}
  validates :ano_letivo, presence: true, length: { minimum: 4}
  validate :verifica_ano

  def verifica_ano
    if ano_letivo < 2020
      errors.add(:ano_letivo, "a partir de 2020")
    end
  end
end

app/controllers/disciplinas_controller.rb
class DisciplinasController < ApplicationController
  #before_action :set_disciplina, only: %i[ show edit update destroy ]

  # GET /disciplinas or /disciplinas.json
  def index
    @disciplinas = Disciplina.all
  end

  # GET /disciplinas/1 or /disciplinas/1.json
  def show
    @disciplina = Disciplina.find(params[:id])
    @atividades = @disciplina.atividades
  end

  # GET /disciplinas/new
  def new
    @disciplina = Disciplina.new
  end

  # GET /disciplinas/1/edit
  def edit
  end

  # POST /disciplinas or /disciplinas.json
  def create
    @turma = Turma.find(disciplina_params[:turma_id])
    @disciplina = Disciplina.new(disciplina_params)
    @turma.disciplinas << @disciplina

    respond_to do |format|
      if @disciplina.save
        format.html { redirect_to @disciplina, notice: "Disciplina was successfully created." }
        format.json { render :show, status: :created, location: @disciplina }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @disciplina.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /disciplinas/1 or /disciplinas/1.json
  def update
    respond_to do |format|
      if @disciplina.update(disciplina_params)
        format.html { redirect_to @disciplina, notice: "Disciplina was successfully updated." }
        format.json { render :show, status: :ok, location: @disciplina }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @disciplina.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /disciplinas/1 or /disciplinas/1.json
  def destroy
    @disciplina.destroy
    respond_to do |format|
      format.html { redirect_to disciplinas_url, notice: "Disciplina was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_disciplina
      @disciplina = Disciplina.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def disciplina_params
      params.require(:disciplina).permit(:nome, :ano_letivo, :turma_id)
    end
end

app/helpers/disciplinas_helper.rb
module DisciplinasHelper
end

app/views/disciplinas/_form.html.erb
<%= form_with(model: disciplina) do |form| %>
  <% if disciplina.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(disciplina.errors.count, "error") %> prohibited this disciplina from being saved:</h2>

      <ul>
        <% disciplina.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome %>
  </div>

  <div class="field">
    <%= form.label :ano_letivo %>
    <%= form.number_field :ano_letivo %>
  </div>

  <h2>Turma:</h2>

  <div class="field">
    <label name="turma_id">Letra:</label>
    <%= form.collection_select(:turma_id, Turma.all, :id, :letra,{:selected => @disciplina.turma_id}, :required => true,)%>
  </div>

  <div class="field">
    <label name="turma1_id">Ano</label>
    <%= form.collection_select(:turma1_id, Turma.all, :id, :ano,{:selected => @disciplina.turma_id}, :required => true)%>
  </div>

  <div class="field">
    <label name="turma2_id">Ano Letivo</label>
    <%= form.collection_select(:turma2_id, Turma.all, :id, :ano_letivo,{:selected => @disciplina.turma_id}, :required => true)%>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/disciplinas/edit.html.erb
<h1>Editing Disciplina</h1>

<%= render 'form', disciplina: @disciplina %>

<%= link_to 'Show', @disciplina %> |
<%= link_to 'Back', disciplinas_path %>

app/views/disciplinas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Disciplinas</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Ano letivo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @disciplinas.each do |disciplina| %>
      <tr>
        <td><%= disciplina.nome %></td>
        <td><%= disciplina.ano_letivo %></td>
        <td><%= link_to 'Show', disciplina %></td>
        <td><%= link_to 'Edit', edit_disciplina_path(disciplina), id:"e-#{disciplina.nome}" %></td>
        <td><%= link_to 'Destroy', disciplina, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Disciplina', new_disciplina_path %> |
<%= link_to 'Voltar', root_path %>

app/views/disciplinas/new.html.erb
<h1>New Disciplina</h1>

<%= render 'form', disciplina: @disciplina %>

<%= link_to 'Back', disciplinas_path %>

app/views/disciplinas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @disciplina.nome %>
</p>

<p>
  <strong>Ano letivo:</strong>
  <%= @disciplina.ano_letivo %>
</p>

<h2>Turma:</h2>

<p>
  <strong>Letra:</strong>
  <%= Turma.find(@disciplina.turma_id).letra %>
</p>

<p>
  <strong>Ano:</strong>
  <%= Turma.find(@disciplina.turma_id).ano %>
</p>

<p>
  <strong>Ano Letivo:</strong>
  <%= Turma.find(@disciplina.turma_id).ano_letivo %>
</p>

<h2>Atividades:</h2>
<p>
  <% @atividades.each do |atividade| %>
    <%= link_to atividade.titulo, atividade_path(atividade, :disciplina_id => @disciplina.id) %> <br>
  <% end %>
</p>

<%= link_to 'Adicionar atividade na disciplina', new_atividade_path(:disciplina_id => @disciplina.id) %> |
<%= link_to 'Voltar', disciplinas_path %>