config/routes.rb
Rails.application.routes.draw do
  resources :avaliacaos
  resources :alunos
  resources :atividades
  resources :disciplinas
  devise_for :users
  resources :turmas
  get 'welcome/index'

  root 'welcome#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/aluno.rb
class Aluno < ApplicationRecord
  belongs_to :turma
  has_many :avaliacaos

  validates :nome, presence: true, length: {in: 5..30}
end

app/controllers/alunos_controller.rb
class AlunosController < ApplicationController
  #before_action :set_aluno, only: %i[ show edit update destroy ]

  # GET /alunos or /alunos.json
  def index
    @alunos = Aluno.all
  end

  # GET /alunos/1 or /alunos/1.json
  def show
    @turma = Turma.find(params[:turma_id])
    @aluno = @turma.alunos.find(params[:id])
  end

  # GET /alunos/new
  def new
    @turma = Turma.find(params[:turma_id])
    @aluno = @turma.alunos.build
  end

  # GET /alunos/1/edit
  def edit
    @turma = Turma.find(params[:turma_id])
    @aluno = @turma.alunos.find(params[:id])
  end

  # POST /alunos or /alunos.json
  def create
    @turma = Turma.find(params[:turma_id])
    @aluno = @turma.alunos.create(aluno_params)

    respond_to do |format|
      if @aluno.save
        format.html { redirect_to turmas_path(@turma), notice: "Aluno was successfully created." }
        format.json { render :show, status: :created, location: @aluno }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @aluno.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /alunos/1 or /alunos/1.json
  def update
    @turma = Turma.find(params[:turma_id])
    @aluno = @turma.alunos.find(params[:id])

    respond_to do |format|
      if @aluno.update(aluno_params)
        format.html { redirect_to turmas_path(@turma), notice: "Aluno was successfully updated." }
        format.json { render :show, status: :ok, location: @aluno }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @aluno.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /alunos/1 or /alunos/1.json
  def destroy
    @turma = Turma.find(params[:turma_id])
    @aluno = @turma.alunos.find(params[:id])

    @aluno.destroy
    respond_to do |format|
      format.html { redirect_to alunos_url, notice: "Aluno was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Only allow a list of trusted parameters through.
    def aluno_params
      params.require(:aluno).permit(:nome)
    end
end

app/helpers/alunos_helper.rb
module AlunosHelper
end

app/views/alunos/_form.html.erb
<%= form_with(model: aluno) do |form| %>
  <% if aluno.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(aluno.errors.count, "error") %> prohibited this aluno from being saved:</h2>

      <ul>
        <% aluno.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome %>
  </div>

  <%= hidden_field_tag(:turma_id, @turma.id) %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/alunos/edit.html.erb
<%= render 'form', {aluno: @aluno, turma: @turma} %>
<%= link_to 'voltar', aluno_path(@aluno, :turma_id => @turma.id) %>

app/views/alunos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Alunos</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @alunos.each do |aluno| %>
      <tr>
        <td><%= aluno.nome %></td>
        <td><%= link_to 'Show', aluno %></td>
        <td><%= link_to 'Edit', edit_aluno_path(aluno) %></td>
        <td><%= link_to 'Destroy', aluno, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Novo Aluno', new_aluno_path %>

app/views/alunos/new.html.erb
<h1>New Aluno</h1>

<%= render 'form', aluno: @aluno %>

<%= link_to 'Back', alunos_path %>

app/views/alunos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @aluno.nome %>
</p>

<%= link_to 'Editar', edit_aluno_path(@aluno, :turma_id => @turma.id) %> |
<%= link_to 'Voltar', turma_path(@turma) %>