config/routes.rb
Rails.application.routes.draw do
  resources :avaliacaos
  resources :alunos
  resources :atividades
  resources :disciplinas
  devise_for :users
  resources :turmas
  get 'welcome/index'

  root 'welcome#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/atividade.rb
class Atividade < ApplicationRecord
  belongs_to :disciplina
  has_many :avaliacaos

  validates :titulo, presence: true, length: {in: 5..20}
  validates :bimestre, length: { is: 1 }
  validates :data, presence: true
  validate :verifica_data

  def verifica_data
    if data.present? && data < Time.zone.today
      errors.add(:data, "nao pode ser no passado")
    end
  end
end

app/controllers/atividades_controller.rb
class AtividadesController < ApplicationController
  #before_action :set_atividade, only: %i[ show edit update destroy ]

  # GET /atividades or /atividades.json
  def index
    @atividades = Atividade.all
  end

  # GET /atividades/1 or /atividades/1.json
  def show
    @disciplina = Disciplina.find(params[:disciplina_id])
    @atividade = @disciplina.atividades.find(params[:id])
  end

  # GET /atividades/new
  def new
    @disciplina = Disciplina.find(params[:disciplina_id])
    @atividade = @disciplina.atividades.build
  end

  # GET /atividades/1/edit
  def edit
    @disciplina = Disciplina.find(params[:disciplina_id])
    @atividade = @disciplina.atividades.find(params[:id])
  end

  # POST /atividades or /atividades.json
  def create
    @disciplina = Disciplina.find(params[:disciplina_id])
    @atividade = @disciplina.atividades.create(atividade_params)

    respond_to do |format|
      if @atividade.save
        format.html { redirect_to disciplinas_path(@disciplina), notice: "Atividade was successfully created." }
        format.json { render :show, status: :created, location: @atividade }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @atividade.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /atividades/1 or /atividades/1.json
  def update
    @disciplina = Disciplina.find(params[:disciplina_id])
    @atividade = @disciplina.atividades.find(params[:id])

    respond_to do |format|
      if @atividade.update(atividade_params)
        format.html { redirect_to disciplinas_path(@disciplina), notice: "Atividade was successfully updated." }
        format.json { render :show, status: :ok, location: @atividade }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @atividade.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /atividades/1 or /atividades/1.json
  def destroy
    @disciplina = Disciplina.find(params[:disciplina_id])
    @atividade = @disciplina.atividades.find(params[:id])

    @atividade.destroy
    respond_to do |format|
      format.html { redirect_to atividades_url, notice: "Atividade was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Only allow a list of trusted parameters through.
    def atividade_params
      params.require(:atividade).permit(:titulo, :descricao, :bimestre, :data)
    end
end

app/helpers/atividades_helper.rb
module AtividadesHelper
end

app/views/atividades/_form.html.erb
<%= form_with(model: atividade) do |form| %>
  <% if atividade.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(atividade.errors.count, "error") %> prohibited this atividade from being saved:</h2>

      <ul>
        <% atividade.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :titulo %>
    <%= form.text_field :titulo %>
  </div>

  <div class="field">
    <%= form.label :descricao %>
    <%= form.text_field :descricao %>
  </div>

  <div class="field">
    <%= form.label :bimestre %>
    <%= form.number_field :bimestre %>
  </div>

  <div class="field">
    <%= form.label :data %>
    <%= form.date_field :data %>
  </div>

  <%= hidden_field_tag(:disciplina_id, @disciplina.id) %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/atividades/edit.html.erb
<%= render 'form', {atividade: @atividade, disciplina: @disciplina} %>

<%= link_to 'voltar', atividade_path(@atividade, :disciplina_id => @disciplina.id) %>

app/views/atividades/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Atividades</h1>

<table>
  <thead>
    <tr>
      <th>Titulo</th>
      <th>Descricao</th>
      <th>Bimestre</th>
      <th>Data</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @atividades.each do |atividade| %>
      <tr>
        <td><%= atividade.titulo %></td>
        <td><%= atividade.descricao %></td>
        <td><%= atividade.bimestre %></td>
        <td><%= atividade.data %></td>
        <td><%= link_to 'Show', atividade %></td>
        <td><%= link_to 'Edit', edit_atividade_path(atividade) %></td>
        <td><%= link_to 'Destroy', atividade, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nova Atividade', new_atividade_path %>

app/views/atividades/new.html.erb
<h1>Nova Atividade</h1>

<%= render 'form', {disciplina: @disciplina, atividade: @atividade } %>
<%= link_to 'Back', atividades_path %>

app/views/atividades/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Titulo:</strong>
  <%= @atividade.titulo %>
</p>

<p>
  <strong>Descricao:</strong>
  <%= @atividade.descricao %>
</p>

<p>
  <strong>Bimestre:</strong>
  <%= @atividade.bimestre %>
</p>

<p>
  <strong>Data:</strong>
  <%= @atividade.data %>
</p>

<%= link_to 'Editar', edit_atividade_path(@atividade, :disciplina_id => @disciplina.id) %> |
<%= link_to 'Voltar', disciplina_path(@disciplina) %>